export const GET_EXERCISES = 'GET_EXERCISES';
export const GET_EXERCISES_SUCCESS = 'GET_EXERCISES_SUCCESS';
export const GET_EXERCISES_ERROR = 'GET_EXERCISES_ERROR';

export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const CREATE_EXERCISE_SUCCESS = 'CREATE_EXERCISE_SUCCESS';
export const CREATE_EXERCISE_ERROR = 'CREATE_EXERCISE_ERROR';

export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const DELETE_EXERCISE_SUCCESS = 'DELETE_EXERCISE_SUCCESS';
export const DELETE_EXERCISE_ERROR = 'DELETE_EXERCISE_ERROR';

export const GET_CREATE_EXERCISE = 'GET_CREATEEXERCISEE';
export const GET_CREATE_EXERCISE_SUCCESS = 'GET_CREATE_EXERCISE_SUCCESS';
export const GET_CREATE_EXERCISE_ERROR = 'GET_CREATE_EXERCISE_ERROR';

export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
export const UPDATE_EXERCISE_SUCCESS = 'UPDATE_TEXERCISESUCCESS';
export const UPDATE_EXERCISE_ERROR = 'UPDATE_EXERCISE_ERROR';
