export const GET_PLANNING_EXERCISES = 'GET_PLANNING_EXERCISES';
export const GET_PLANNING_EXERCISES_SUCCESS = 'GET_PLANNING_EXERCISES_SUCCESS';
export const GET_PLANNING_EXERCISES_ERROR = 'GET_PLANNING_EXERCISES_ERROR';
export const UPDATE_PLANNING_EXERCISES = 'UPDATE_PLANNING_EXERCISES';
export const UPDATE_PLANNING_EXERCISES_SUCCESS = 'UPDATE_PLANNING_EXERCISES_SUCCESS';
export const UPDATE_PLANNING_EXERCISES_ERROR = 'UPDATE_PLANNING_EXERCISES_ERROR';
