export const GET_PLANNING_EXERCISES = 'GET_PLANNING_EXERCISES';
export const GET_PLANNING_EXERCISES_SUCCESS = 'GET_PLANNING_EXERCISES_SUCCESS';
export const GET_PLANNING_EXERCISES_ERROR = 'GET_PLANNING_EXERCISES_ERROR';
