export const GET_TABLES = 'GET_TABLES';
export const GET_TABLES_SUCCESS = 'GET_TABLES_SUCCESS';
export const GET_TABLES_ERROR = 'GET_TABLES_ERROR';

export const CREATE_TABLE = 'CREATE_TABLE';
export const CREATE_TABLE_SUCCESS = 'CREATE_TABLE_SUCCESS';
export const CREATE_TABLE_ERROR = 'CREATE_TABLE_ERROR';

export const DELETE_TABLE = 'DELETE_TABLE';
export const DELETE_TABLE_SUCCESS = 'DELETE_TABLE_SUCCESS';
export const DELETE_TABLE_ERROR = 'DELETE_TABLE_ERROR';

export const GET_CREATE_TABLE = 'GET_CREATE_TABLE';
export const GET_CREATE_TABLE_SUCCESS = 'GET_CREATE_TABLE_SUCCESS';
export const GET_CREATE_TABLE_ERROR = 'GET_CREATE_TABLE_ERROR';

export const UPDATE_TABLE = 'UPDATE_TABLE';
export const UPDATE_TABLE_SUCCESS = 'UPDATE_TABLE_SUCCESS';
export const UPDATE_TABLE_ERROR = 'UPDATE_TABLE_ERROR';
