export const UPLOAD_PICTURE = 'UPLOAD_PICTURE';
export const UPLOAD_PICTURE_SUCCESS = 'UPLOAD_PICTURE_SUCCESS';
export const UPLOAD_PICTURE_ERROR = 'UPLOAD_PICTURE_ERROR';

export const UPLOAD_TEXT = 'UPLOAD_TEXT';
export const UPLOAD_TEXT_SUCCESS = 'UPLOAD_TEXT_SUCCESS';
export const UPLOAD_TEXT_ERROR = 'UPLOAD_TEXT_ERROR';

export const GET_IMAGES = 'GET_IMAGES';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_ERROR = 'GET_IMAGES_ERROR';
