export const UPLOAD_PICTURE = 'UPLOAD_PICTURE';
export const UPLOAD_PICTURE_SUCCESS = 'UPLOAD_PICTURE_SUCCESS';
export const UPLOAD_PICTURE_ERROR = 'UPLOAD_PICTURE_ERROR';

export const UPLOAD_TEXT = 'UPLOAD_TEXT';
export const UPLOAD_TEXT_SUCCESS = 'UPLOAD_TEXT_SUCCESS';
export const UPLOAD_TEXT_ERROR = 'UPLOAD_TEXT_ERROR';
