// hello world actions
export const HELLO_WORLD = 'HELLO_WORLD';
export const HELLO_WORLD_END = 'HELLO_WORLD_END';
// auth actions
export const DO_LOGIN = 'DO_LOGIN';
export const DO_LOGOUT = 'DO_LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const DO_REGISTER = 'DO_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
//administration Menu
export const CREATE_MENU = 'CREATE_MENU';
export const CREATE_MENU_SUCCESS = 'CREATE_MENU_SUCCESS';
export const CREATE_MENU_ERROR = 'CREATE_MENU_ERROR';
export const GET_MENU = 'GET_MENU';
export const GET_MENU_NAME = 'GET_MENU_NAME'
export const GET_MENU_NAME_ERROR = 'GET_MENU_NAME_ERROR'
export const GET_MENU_NAME_SUCCESS = 'GET_MENU_NAME_SUCCESS'
export const GET_MENU_ERROR = 'GET_MENU_ERROR';
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
export const DELETE_MENU = 'DELETE_MENU';
export const DELETE_MENU_SUCCESS = 'DELETE_MENU_SUCCESS';
export const DELETE_MENU_ERROR = 'DELETE_MENU_ERROR';
export const UPDATE_MENU = 'UPDATE_MENU';
export const UPDATE_MENU_SUCCESS = 'UPDATE_MENU_SUCCESS';
export const UPDATE_MENU_ERROR = 'UPDATE_MENU_ERROR';
//administration TimeFood
export const GET_TIMEFOOD = 'GET_TIMEFOOD';
export const GET_TIMEFOOD_SUCCESS = 'GET_TIMEFOOD_SUCCESS';
export const GET_TIMEFOOD_ERROR = 'GET_TIMEFOOD_ERROR';
export const GET_TIMEFOODS = 'GET_TIMEFOODS';
export const GET_TIMEFOODS_SUCCESS = 'GET_TIMEFOODS_SUCCESS';
export const GET_TIMEFOODS_ERROR = 'GET_TIMEFOODS_ERROR';
export const CREATE_TIMEFOOD = 'CREATE_TIMEFOOD';
export const CREATE_TIMEFOOD_SUCCESS = 'CREATE_TIMEFOOD_SUCCESS';
export const CREATE_TIMEFOOD_ERROR = 'CREATE_TIMEFOOD_ERROR';
export const DELETE_TIMEFOOD = 'DELETE_TIMEFOOD';
export const DELETE_TIMEFOOD_SUCCESS = 'DELETE_TIMEFOOD_SUCCESS';
export const DELETE_TIMEFOOD_ERROR = 'DELETE_TIMEFOOD_ERROR';
export const UPDATE_TIMEFOOD = 'UPDATE_TIMEFOOD';
export const UPDATE_TIMEFOOD_SUCCESS = 'UPDATE_TIMEFOOD_SUCCESS';
export const UPDATE_TIMEFOOD_ERROR = 'UPDATE_TIMEFOOD_ERROR';
//Administration Foods
export const GET_FOOD = 'GET_FOOD';
export const GET_FOOD_SUCCESS = 'GET_FOOD_SUCCESS';
export const GET_FOOD_ERROR = 'GET_FOOD_ERROR';
export const GET_FOODS = 'GET_FOODS';
export const GET_FOODS_SUCCESS = 'GET_FOODS_SUCCESS';
export const GET_FOODS_ERROR = 'GET_FOODS_ERROR';
export const CREATE_FOOD = 'CREATE_FOOD';
export const CREATE_FOOD_SUCCESS = 'CREATE_FOOD_SUCCESS';
export const CREATE_FOOD_ERROR = 'CREATE_FOOD_ERROR';
export const DELETE_FOOD = 'DELETE_FOOD';
export const DELETE_FOOD_SUCCESS = 'DELETE_FOOD_SUCCESS';
export const DELETE_FOOD_ERROR = 'DELETE_FOOD_ERROR';
export const UPDATE_FOOD = 'UPDATE_FOOD';
export const UPDATE_FOOD_SUCCESS = 'UPDATE_FOOD_SUCCESS';
export const UPDATE_FOOD_ERROR = 'UPDATE_FOOD_ERROR';
// notifications actions
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

// exercise table actions
export const CREATE_EXERCISE_TABLE = 'CREATE_EXERCISE_TABLE';
export const CREATE_EXERCISE_TABLE_SUCCESS = 'CREATE_EXERCISE_TABLE_SUCCESS';
export const CREATE_EXERCISE_TABLE_ERROR = 'CREATE_EXERCISE_TABLE_ERROR';

export const DELETE_EXERCISE_TABLE = 'DELETE_EXERCISE_TABLE';
export const DELETE_EXERCISE_TABLE_SUCCESS = 'DELETE_EXERCISE_TABLE_SUCCESS';
export const DELETE_EXERCISE_TABLE_ERROR = 'DELETE_EXERCISE_TABLE_ERROR';

export const UPDATE_EXERCISE_TABLE = 'UPDATE_EXERCISE_TABLE';
export const UPDATE_EXERCISE_TABLE_SUCCESS = 'UPDATE_EXERCISE_TABLE_SUCCESS';
export const UPDATE_EXERCISE_TABLE_ERROR = 'UPDATE_EXERCISE_TABLE_ERROR';

export const GET_EXERCISE_TABLE = 'GET_EXERCISE_TABLE';
export const GET_EXERCISE_TABLE_SUCCESS = 'GET_EXERCISE_TABLE_SUCCESS';
export const GET_EXERCISE_TABLE_ERROR = 'GET_EXERCISE_TABLE_ERROR';

export const GET_EXERCISE_TABLE_NAME = 'GET_EXERCISE_TABLE_NAME';
export const GET_EXERCISE_TABLE_NAME_ERROR = 'GET_EXERCISE_TABLE_NAME_ERROR';
export const GET_EXERCISE_TABLE_NAME_SUCCESS = 'GET_EXERCISE_TABLE_NAME_SUCCESS';

// exercise actions
export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const CREATE_EXERCISE_SUCCESS = 'CREATE_EXERCISE_SUCCESS';
export const CREATE_EXERCISE_ERROR = 'CREATE_EXERCISE_ERROR';

export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const DELETE_EXERCISE_SUCCESS = 'DELETE_EXERCISE_SUCCESS';
export const DELETE_EXERCISE_ERROR = 'DELETE_EXERCISE_ERROR';

export const UPDATE_EXERCISE= 'UPDATE_EXERCISE';
export const UPDATE_EXERCISE_SUCCESS = 'UPDATE_EXERCISE_SUCCESS';
export const UPDATE_EXERCISE_ERROR = 'UPDATE_EXERCISE_ERROR';

export const GET_EXERCISE = 'GET_EXERCISE';
export const GET_EXERCISE_SUCCESS = 'GET_EXERCISE_SUCCESS';
export const GET_EXERCISE_ERROR = 'GET_EXERCISE_ERROR';
