// hello world actions
export const HELLO_WORLD = 'HELLO_WORLD';
export const HELLO_WORLD_END = 'HELLO_WORLD_END';
// auth actions
export const DO_LOGIN = 'DO_LOGIN';
export const DO_LOGOUT = 'DO_LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const DO_REGISTER = 'DO_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
//administration Menu
export const CREATE_MENU = 'CREATE_MENU';
export const CREATE_MENU_SUCCESS = 'CREATE_MENU_SUCCESS';
export const CREATE_MENU_ERROR = 'CREATE_MENU_ERROR';
export const GET_MENU = 'GET_MENU';
export const GET_MENU_NAME = 'GET_MENU_NAME'
export const GET_MENU_NAME_ERROR = 'GET_MENU_NAME_ERROR'
export const GET_MENU_NAME_SUCCESS = 'GET_MENU_NAME_SUCCESS'
export const GET_MENU_ERROR = 'GET_MENU_ERROR';
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
export const DELETE_MENU = 'DELETE_MENU';
export const DELETE_MENU_SUCCESS = 'DELETE_MENU_SUCCESS';
export const DELETE_MENU_ERROR = 'DELETE_MENU_ERROR';
export const UPDATE_MENU = 'UPDATE_MENU';
export const UPDATE_MENU_SUCCESS = 'UPDATE_MENU_SUCCESS';
export const UPDATE_MENU_ERROR = 'UPDATE_MENU_ERROR';
//administration TimeFood
export const GET_TIMEFOOD = 'GET_TIMEFOOD';
export const GET_TIMEFOOD_SUCCESS = 'GET_TIMEFOOD_SUCCESS';
export const GET_TIMEFOOD_ERROR = 'GET_TIMEFOOD_ERROR';
export const GET_TIMEFOODS = 'GET_TIMEFOODS';
export const GET_TIMEFOODS_SUCCESS = 'GET_TIMEFOODS_SUCCESS';
export const GET_TIMEFOODS_ERROR = 'GET_TIMEFOODS_ERROR';
export const CREATE_TIMEFOOD = 'CREATE_TIMEFOOD';
export const CREATE_TIMEFOOD_SUCCESS = 'CREATE_TIMEFOOD_SUCCESS';
export const CREATE_TIMEFOOD_ERROR = 'CREATE_TIMEFOOD_ERROR';
export const DELETE_TIMEFOOD = 'DELETE_TIMEFOOD';
export const DELETE_TIMEFOOD_SUCCESS = 'DELETE_TIMEFOOD_SUCCESS';
export const DELETE_TIMEFOOD_ERROR = 'DELETE_TIMEFOOD_ERROR';
export const UPDATE_TIMEFOOD = 'UPDATE_TIMEFOOD';
export const UPDATE_TIMEFOOD_SUCCESS = 'UPDATE_TIMEFOOD_SUCCESS';
export const UPDATE_TIMEFOOD_ERROR = 'UPDATE_TIMEFOOD_ERROR';
// notifications actions
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
// exercise actions
export const CREATE_EXERCISE_TABLE = 'CREATE_EXERCISE_TABLE';
export const CREATE_EXERCISE_TABLE_SUCCESS = 'CREATE_EXERCISE_TABLE_SUCCESS';
export const CREATE_EXERCISE_TABLE_ERROR = 'CREATE_EXERCISE_TABLE_ERROR';
